version: '2'

services:
  mariadb:
    image: mariadb:latest
    container_name: dev-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - "3306:3306"
    volumes_from:
      - datastore

  datastore:
    image: busybox
    container_name: dev-datastore
    tty: true
    volumes:
      - /var/lib/mysql

  web:
    build: ./webphp
    image: apache-php:dev
    container_name: dev-php
    ports:
      - "80:80"
    volumes:
      - /d/dockerp/lamp/webphp/public-html:/var/www/html
    links:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev-myadmin
    ports:
      - "8080:80"
    links:
      - "mariadb:db"
